package:
  name: emcee
  version: "2.1.0"

source:
  fn: emcee-2.1.0.tar.gz
  url: https://pypi.python.org/packages/source/e/emcee/emcee-2.1.0.tar.gz
  md5: c6b6fad05c824d40671d4a4fc58dfff7

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy

  run:
    - python
    - numpy

test:
  # Python imports
  imports:
    - emcee

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.
    - "python -c 'import emcee; emcee.test()'"

about:
  home: http://dan.iel.fm/emcee/
  license:  MIT License
  summary: 'Kick ass affine-invariant ensemble MCMC sampling'
