package:
  name: cartopy
  version: 0.11.2
source:
  git_url: https://github.com/SciTools/cartopy.git
  git_tag: v0.11.2

build:
  number: 0

requirements:
  build:
    - python
    - six
    - numpy
    - cython
    - proj4
    - shapely
    - geos >=3.4.2
  run:
    - python
    - six
    - mock
    - nose
    - pil
    - owslib
    - numpy
    - proj4
    - shapely
    - scipy
    - pyshp
    - matplotlib
    - geos >=3.4.2

test:
  imports:
    - cartopy

about:
  home: http://scitools.org.uk/cartopy
  license: GNU LGPL
  summary: 'A library providing cartographic tools for python'
