package:
  name: pystan
  version: !!str 2.2.0.1

source:
  fn: pystan-2.2.0.1.tar.gz
  url: https://pypi.python.org/packages/source/p/pystan/pystan-2.2.0.1.tar.gz
  md5: 06f5bca8105c8fa96286183f57af1a61
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pystan = pystan:main
    #
    # Would create an entry point called pystan that calls pystan.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - cython >=0.19
    - numpy

  run:
    - python
    - cython >=0.19
    - numpy

test:
  # Python imports
  imports:
    - pystan

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/stan-dev/pystan
  license: GNU General Public License v3 (GPLv3)
  summary: 'Python interface to Stan, a package for Bayesian inference'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
