package:
  name: dill
  version: !!str 0.2.1

source:
  fn: dill-0.2.1.tgz
  url: https://pypi.python.org/packages/source/d/dill/dill-0.2.1.tgz
  md5: 66f4d8fff8724568bde03e421bf520bb
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - dill = dill:main
    #
    # Would create an entry point called dill that calls dill.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - dill

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.cacr.caltech.edu/~mmckerns/dill.htm
  license: 3-clause BSD
  summary: 'serialize all of python (almost)'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
