package:
  name: basemap
  version: "1.0.7"
source:
  fn:  basemap-1.0.7.tar.gz
  url: https://downloads.sourceforge.net/project/matplotlib/matplotlib-toolkits/basemap-1.0.7/basemap-1.0.7.tar.gz
  md5: 48c0557ced9e2c6e440b28b3caff2de8

build:
  # prefer our build to continuum's (so we can use a later geos version
  # compatible with cartopy)
  number: 1

requirements:
  build:
    - python
    - numpy
    - geos >=3.4.2
  run:
    - python
    - numpy
    - matplotlib
    - geos >=3.4.2

test:
  imports:
    - mpl_toolkits.basemap

about:
  home: http://matplotlib.org/basemap
  license: GNU GPL
