package:
  name: pyproj
  version: "1.9.3"

source:
  fn: pyproj-1.9.3.tar.gz
  url: https://pypi.python.org/packages/source/p/pyproj/pyproj-1.9.3.tar.gz
  md5: ad0ac0602b6373c4203b4d0774445694

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - pyproj

about:
  home: http://code.google.com/p/pyproj/
  license: OSI Approved
  summary: 'Python interface to PROJ.4 library'
